languageCode: "en-us"
title: "Home"
theme: "salient"

params:
  # parts
  clock: true
  search: true # search box inline, if you don't apply Chromium patches this may be useful

  colors: # https://tailwindcss.com/docs/customizing-colors
    text: black
    highlight: gray

  featured:
    - name: "YouTube"
      logo: "/images/youtube.png"
      url: "https://youtube.com"
    - name: "Nextcloud"
      logo: "/images/cloud.png"
      url: "https://thefluegel.me"
    - name: "NAS"
      logo: "/images/dsm.png"
      url: "https://nas.thefluegel.me"
    - name: "Twitter"
      logo: "/images/twitter.png"
      url: "https://twitter.com"
    - name: "Wiki"
      logo: "/images/wikijs.png"
      url: "https://wiki.thefluegel.me"
    - name: "Github"
      logo: "/images/github.png"
      url: "https://github.com/"

  standard:
    - name: "Network"
      items:
        - name: "Fritz!Box"
          url: "http://192.168.178.1"
        - name: "Speedtest"
          url: "http://speedtest.net"
        - name: "Pi-Hole"
          url: "http://192.168.178.39/admin"
        - name: "Uberspace"
          url: "https://dashboard.uberspace.de"
        - name: "PlexPy"
          url: "http://192.168.178.35:8011"

    - name: "Media"
      items:
        - name: "Moments"
          url: "http://nas.thefluegel.me/moments"
        - name: "Netflix"
          url: "http://netflix.com"
        - name: "Disney+"
          url: "https://disneyplus.com"

    - name: "Uni"
      items:
        - name: "Virtu"
          url: "https://virtuohm.ohmportal.de"
        - name: "Study"
          icon: "fas fa-university"
          url: "https://studium.ohmportal.de"
        - name: "Moodle"
          url: "https://elearning.ohmportal.de"
        - name: "My Ohmportal"
          url: "https://my.ohmportal.de"

    - name: "Banking"
      items:
        - name: "Sparkasse"
          url: "https://www.sparkasse-fuerth.de"
        - name: "N26"
          url: "https://app.n26.com/login"
        - name: "PayPal"
          icon: "fab fa-paypal"
          url: "https://www.paypal.com/de/home"

    - name: "Other"
      items:
        - name: "Reddit"
          url: "https://www.reddit.com"
        - name: "Pocket"
          url: "https://getpocket.com"
        - name: "Tagesschau"
          url: "https://www.tagesschau.de/"
        - name: "Amazon"
          url: "https://www.amazon.de"

# Do not change
build:
  writeStats: true
